--CREATE TABLE Users
--(
--	UserId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
--	UserName NVARCHAR(20) NOT NULL UNIQUE,
--	[Password] NVARCHAR(20) NOT NULL,
--);

--CREATE TABLE ToDos
--(
--	ToDoId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
--	[Description] NVARCHAR(100) NOT NULL,
--	Complete BIT NOT NULL,
--	Due_Date DATETIME NOT NULL,
--	UserID NVARCHAR(450) FOREIGN KEY REFERENCES AspNetUsers(Id)
--);

--DROP TABLE ToDos;
--SELECT * FROM Users
--SELECT * FROM ToDos
